import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const thamaniyah = localFont({
  src: "../public/fonts/woff2/thmanyahserifdisplay-Regular.woff2",
  variable: "--font-thamaniyah",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={`${thamaniyah.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">{children}</body>
    </html>
  );
}
